<?php

namespace Tests;

//use AjCastro\ScribeTdd\Tests\ScribeTddSetup;
use App\Models\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
//        $this->setUpScribeTdd();
    }

    protected function getActingUser() {
        return User::query()->firstOrFail();
    }
}
